export interface Theme {
  name: string;
  colors: Record<string, string>;
}

export const themes: Record<string, Theme> = {
  onyx: {
    name: "Huyền Mặc",
    colors: {
      "--color-background": "#111827",
      "--color-surface": "#1f2937",
      "--color-terminal": "rgba(0, 0, 0, 0.5)",
      "--color-border": "#374151",
      "--color-text-base": "#f9fafb",
      "--color-text-muted": "#9ca3af",
      "--color-text-inverse": "#111827",
      "--color-primary": "#0891b2",
      "--color-primary-hover": "#06b6d4",
      "--color-primary-text": "#ffffff",
      "--color-secondary": "#7c3aed",
      "--color-secondary-hover": "#8b5cf6",
      "--color-accent": "#22d3ee",
      "--color-accent-glow": "#06b6d4",
      "--color-xp": "#67e8f9",
      "--color-gold": "#facc15",
      "--color-success": "#4ade80",
      "--color-success-bg": "#16a34a",
      "--color-danger": "#f87171",
    },
  },
  jade: {
    name: "Thanh Ngọc",
    colors: {
      "--color-background": "#072721",
      "--color-surface": "#0c3f36",
      "--color-terminal": "rgba(4, 24, 20, 0.5)",
      "--color-border": "#1e6054",
      "--color-text-base": "#e2fdf5",
      "--color-text-muted": "#a3e6c3",
      "--color-text-inverse": "#072721",
      "--color-primary": "#10b981",
      "--color-primary-hover": "#34d399",
      "--color-primary-text": "#ffffff",
      "--color-secondary": "#059669",
      "--color-secondary-hover": "#10b981",
      "--color-accent": "#6ee7b7",
      "--color-accent-glow": "#10b981",
      "--color-xp": "#a7f3d0",
      "--color-gold": "#fde047",
      "--color-success": "#86efac",
      "--color-success-bg": "#22c55e",
      "--color-danger": "#fb7185",
    },
  },
  azure: {
    name: "Bích Hải",
    colors: {
      "--color-background": "#0c2444",
      "--color-surface": "#123566",
      "--color-terminal": "rgba(5, 16, 36, 0.5)",
      "--color-border": "#1a4a8d",
      "--color-text-base": "#e0f2fe",
      "--color-text-muted": "#bae6fd",
      "--color-text-inverse": "#0c2444",
      "--color-primary": "#0ea5e9",
      "--color-primary-hover": "#38bdf8",
      "--color-primary-text": "#ffffff",
      "--color-secondary": "#3b82f6",
      "--color-secondary-hover": "#60a5fa",
      "--color-accent": "#7dd3fc",
      "--color-accent-glow": "#0ea5e9",
      "--color-xp": "#bae6fd",
      "--color-gold": "#facc15",
      "--color-success": "#4ade80",
      "--color-success-bg": "#16a34a",
      "--color-danger": "#f472b6",
    },
  },
  golden: {
    name: "Kim Ô",
    colors: {
      "--color-background": "#2d1d0c",
      "--color-surface": "#4d3216",
      "--color-terminal": "rgba(22, 13, 5, 0.5)",
      "--color-border": "#734922",
      "--color-text-base": "#fffbeb",
      "--color-text-muted": "#fde68a",
      "--color-text-inverse": "#2d1d0c",
      "--color-primary": "#f59e0b",
      "--color-primary-hover": "#facc15",
      "--color-primary-text": "#451a03",
      "--color-secondary": "#d97706",
      "--color-secondary-hover": "#f59e0b",
      "--color-accent": "#fcd34d",
      "--color-accent-glow": "#f59e0b",
      "--color-xp": "#fde047",
      "--color-gold": "#fef08a",
      "--color-success": "#bef264",
      "--color-success-bg": "#84cc16",
      "--color-danger": "#fca5a5",
    },
  },
  violet: {
    name: "Tử Vận",
    colors: {
      "--color-background": "#291c3d",
      "--color-surface": "#412e5f",
      "--color-terminal": "rgba(20, 13, 33, 0.5)",
      "--color-border": "#5c4182",
      "--color-text-base": "#f5f3ff",
      "--color-text-muted": "#ddd6fe",
      "--color-text-inverse": "#291c3d",
      "--color-primary": "#a78bfa",
      "--color-primary-hover": "#c4b5fd",
      "--color-primary-text": "#1e1b4b",
      "--color-secondary": "#8b5cf6",
      "--color-secondary-hover": "#a78bfa",
      "--color-accent": "#c4b5fd",
      "--color-accent-glow": "#8b5cf6",
      "--color-xp": "#ddd6fe",
      "--color-gold": "#facc15",
      "--color-success": "#a3e635",
      "--color-success-bg": "#65a30d",
      "--color-danger": "#fda4af",
    },
  },
  crimson: {
    name: "Huyết Hỏa",
    colors: {
      "--color-background": "#3d1c1a",
      "--color-surface": "#5f2e2a",
      "--color-terminal": "rgba(33, 13, 12, 0.5)",
      "--color-border": "#82413b",
      "--color-text-base": "#fff1f2",
      "--color-text-muted": "#fecdd3",
      "--color-text-inverse": "#3d1c1a",
      "--color-primary": "#ef4444",
      "--color-primary-hover": "#f87171",
      "--color-primary-text": "#ffffff",
      "--color-secondary": "#f97316",
      "--color-secondary-hover": "#fb923c",
      "--color-accent": "#fca5a5",
      "--color-accent-glow": "#ef4444",
      "--color-xp": "#fecaca",
      "--color-gold": "#fbbf24",
      "--color-success": "#84cc16",
      "--color-success-bg": "#4d7c0f",
      "--color-danger": "#ff8c8c",
    },
  },
};
